DROP TABLE IF EXISTS WORKER, HABILITAÇÕES, SALES, DEPARTAMENTO, FORNECEDOR, CLIENTE,ARMAZEM,FORNECE,ENTREGA;

CREATE TABLE WORKER(
	Id 			INT PRIMARY KEY AUTO_INCREMENT,
	Email 		VARCHAR(64) NOT NULL,
	
	Name 		VARCHAR(128) NOT NULL,
	Sexo 		ENUM('M','F') NOT NULL,
	DataNasc	DATE NOT NULL,

	Rua 		VARCHAR(168) NOT NULL,
	Num 		INT NOT NULL,
	Andar 		INT DEFAULT NULL,
	Cidade 		VARCHAR(64) NOT NULL,
	NumTele 	INT NOT NULL,
	Supervisor	INT DEFAULT NULL,
	
	Salário 	INT NOT NULL,
	IdDep 		INT NOT NULL,

	FOREIGN KEY (Supervisor) REFERENCES WORKER(Id)
);

CREATE TABLE HABILITAÇÕES (
	Worker 		INT NOT NULL,
	Sales 		INT NOT NULL,
	
	Grau 		VARCHAR(64) NOT NULL,
	Instituição VARCHAR(64) NOT NULL,
	Ano 		INT NOT NULL,
	
	PRIMARY KEY (Worker,Sales,Grau,Instituição,Ano),
	FOREIGN KEY (Worker) REFERENCES WORKER(Id)
);

CREATE TABLE SALES (
	Id 			INT PRIMARY KEY AUTO_INCREMENT,
	Email 		VARCHAR(64) NOT NULL,
	
	Name 		VARCHAR(128) NOT NULL,
	DataNasc 	DATE NOT NULL,
	Sexo 		ENUM('M','F') NOT NULL,
	
	Rua 		VARCHAR(168) NOT NULL,
	Num 		INT NOT NULL,
	Andar 		INT DEFAULT NULL,
	Cidade 		VARCHAR(64) NOT NULL,
	NumTele 	INT NOT NULL,
	
	Salário 	INT NOT NULL,
	Vendas 		INT NOT NULL,
	Bónus 		INT NOT NULL

);

CREATE TABLE DEPARTAMENTO (
	IdDep 		INT PRIMARY KEY AUTO_INCREMENT,
	FOREIGN KEY (IdDep) REFERENCES WORKER(Id),
	Sala VARCHAR(64)
);

ALTER TABLE WORKER ADD FOREIGN KEY(IdDep) REFERENCES DEPARTAMENTO(IdDep);
ALTER TABLE HABILITAÇÕES ADD FOREIGN KEY(Sales) REFERENCES SALES(Id);

CREATE TABLE FORNECEDOR (
	
	Nome VARCHAR(128) NOT NULL,

	Rua 		VARCHAR(168) NOT NULL,
	Num 		INT NOT NULL,
	Andar 		INT DEFAULT NULL,
	Cidade 		VARCHAR(64) NOT NULL,

	PRIMARY KEY(Nome)
);

CREATE TABLE CLIENTE (
	Email 		VARCHAR(64) NOT NULL,
	NomeCliente VARCHAR(128) NOT NULL,
	NomeEmpresa VARCHAR(128) NOT NULL,

	Rua 		VARCHAR(168) NOT NULL,
	Num 		INT NOT NULL,
	Andar 		INT DEFAULT NULL,
	Cidade 		VARCHAR(64) NOT NULL,
	
	DataInicio 	DATE NOT NULL,
	NumTele 	INT NOT NULL,

	PRIMARY KEY(Email)
);

CREATE TABLE ARMAZEM (
	Nome 		VARCHAR(128) NOT NULL,

	Rua 		VARCHAR(168) NOT NULL,
	Num 		INT NOT NULL,
	Andar 		INT DEFAULT NULL,
	Cidade 		VARCHAR(64) NOT NULL,

	Gerente 	INT NOT NULL,

	PRIMARY KEY(Nome,Gerente),
	FOREIGN KEY(Gerente) REFERENCES WORKER(Id)
);

CREATE TABLE FORNECE (
	Fornecedor 	VARCHAR(128) NOT NULL,
	Armazem 	VARCHAR(128) NOT NULL,

	PRIMARY KEY(Fornecedor,Armazem),
	FOREIGN KEY(Fornecedor) REFERENCES FORNECEDOR(Nome),
	FOREIGN KEY(Armazem) REFERENCES ARMAZEM(Nome)
);


CREATE TABLE ENTREGA (
	Armazem 	VARCHAR(128) NOT NULL,
	Cliente 	VARCHAR(64) NOT NULL,

	PRIMARY KEY(Armazem,CLiente),

	FOREIGN KEY(Armazem) REFERENCES ARMAZEM(Nome),
	FOREIGN KEY(Cliente) REFERENCES CLIENTE(Email)
);



